4.1 Exercise on Functions:**
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).


In [4]:
def convert_units(conversion_type, value):
    """
    Converts units between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion selected.
    value (float): Value to convert.

    Returns:
    float: Converted result.
    """

    if conversion_type == "1":
        return value * 3.28084  # meters to feet
    elif conversion_type == "2":
        return value / 3.28084  # feet to meters
    elif conversion_type == "3":
        return value * 2.20462  # kg to lbs
    elif conversion_type == "4":
        return value / 2.20462  # lbs to kg
    elif conversion_type == "5":
        return value * 0.264172  # liters to gallons
    elif conversion_type == "6":
        return value / 0.264172  # gallons to liters
    else:
        raise ValueError("Invalid conversion type.")

In [2]:
print("Unit Converter Program")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

choice = input("Enter choice (1-6): ")

try:
    value = float(input("Enter value: "))
    result = convert_units(choice, value)
    print("Converted value:", result)

except ValueError as e:
    print("Error:", e)

except Exception:
    print("Invalid input. Please enter numeric value.")

Unit Converter Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6): 1
Enter value: 122
Converted value: 400.26248


**Task - 2:**
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [5]:
def calculate_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average of numbers.
    """
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum value from a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Maximum value.
    """
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum value from a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Minimum value.
    """
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return min(numbers)

In [6]:
print("Mathematical Operations Program")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

choice = input("Choose operation (1-4): ")

try:
    user_input = input("Enter numbers separated by spaces: ")

    # Convert string input to list of floats
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("You entered an empty list.")

    if choice == "1":
        result = calculate_sum(numbers)
    elif choice == "2":
        result = calculate_average(numbers)
    elif choice == "3":
        result = find_max(numbers)
    elif choice == "4":
        result = find_min(numbers)
    else:
        raise ValueError("Invalid operation selected.")

    print("Result:", result)

except ValueError as e:
    print("Error:", e)

except Exception:
    print("Invalid input. Please enter numeric values only.")

Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Choose operation (1-4): 1
Enter numbers separated by spaces: 12 12
Result: 24.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [7]:
def extract_every_other(lst):
    return lst[::2]

In [ ]:
test_list = [1, 2, 3, 4, 5, 6]
print(extract_every_other(test_list))

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

In [ ]:
test_list = [1, 2, 3, 4, 5, 6]
print(get_sublist(test_list, 2, 4))

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]

In [ ]:
test_list = [1, 2, 3, 4, 5]
print(reverse_list(test_list))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

In [ ]:
test_list = [1, 2, 3, 4, 5]
print(remove_first_last(test_list))

[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].


In [ ]:
def get_first_n(lst, n):
    return lst[:n]

In [ ]:
test_list = [1, 2, 3, 4, 5]
print(get_first_n(test_list, 3))

[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].


In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

In [ ]:
test_list = [1, 2, 3, 4, 5]
print(get_last_n(test_list, 2))

[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

In [ ]:
test_list = [1, 2, 3, 4, 5, 6]
print(reverse_skip(test_list))

[5, 3, 1]


4.3 – Nested Lists


1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):

    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

In [ ]:
nested = [[1, 2], [3, 4], [5]]
print(flatten(nested))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.


In [ ]:
def access_nested_element(lst, indices):

    element = lst
    for index in indices:
        element = element[index]
    return element

In [ ]:
nested = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(nested, [1,2]))

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.


In [ ]:
def sum_nested(lst):

    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call
        else:
            total += item
    return total

In [ ]:
nested = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested))


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].


In [ ]:
def remove_element(lst, elem):

    new_list = []

    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        elif item != elem:
            new_list.append(item)

    return new_list

In [ ]:
nested = [[1, 2], [3, 2], [4, 5]]
print(remove_element(nested, 2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [11]:
def find_max(lst):

    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))  # recursive
        else:
            maximum = max(maximum, item)

    return maximum

In [12]:
nested = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested))

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [13]:
def count_occurrences(lst, elem):

    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # recursive call
        elif item == elem:
            count += 1

    return count

In [14]:
nested = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(nested, 2))

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [15]:
def deep_flatten(lst):

    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)

    return flat_list

In [16]:
nested = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
def average_nested(lst):

    def helper(sublist):
        total = 0
        count = 0

        for item in sublist:
            if isinstance(item, list):
                sub_total, sub_count = helper(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1

        return total, count

    total_sum, total_count = helper(lst)

    if total_count == 0:
        raise ValueError("List contains no numeric elements.")

    return total_sum / total_count

In [18]:
nested = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested))

3.5


**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:
Complete the following Tasks:


In [19]:
import numpy as np

1. Initialize an empty array with size 2X2.


In [20]:
empty_array = np.empty((2, 2))
print(empty_array)

[[2.36522663e-316 0.00000000e+000]
 [3.29257015e+161 2.30955689e+161]]


2. Initialize an all one array with size 4X2.


In [21]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [22]:
full_array = np.full((3, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [23]:
a = np.array([[1, 2], [3, 4]])

zeros_like_array = np.zeros_like(a)
print(zeros_like_array)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [24]:
ones_like_array = np.ones_like(a)
print(ones_like_array)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [25]:
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print(array_from_list)

[1 2 3 4]


---
**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [26]:
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [27]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [28]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [29]:
random_array = np.random.random(30)
print("Mean:", random_array.mean())

Mean: 0.5159415162902456


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [30]:
arr10 = np.random.random((10, 10))
print("Min:", arr10.min())
print("Max:", arr10.max())

Min: 0.010218723842027266
Max: 0.9958664622782052


6. Create a zero array of size 10 and replace 5th element with 1.


In [31]:
arr_zero = np.zeros(10)
arr_zero[4] = 1
print(arr_zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [34]:
arr = np.array([1, 2, 0, 0, 4, 0])
print(arr[::-1])

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [35]:
arr_border = np.ones((5, 5))
arr_border[1:-1, 1:-1] = 0
print(arr_border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [36]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**
For the following arrays:

x = np.array([[1,2],[3,5]])

y = np.array([[5,6],[7,8]])

v = np.array([9,10])

w = np.array([11,12])

Complete all the task using numpy:


In [39]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.


In [40]:
print(x + y)

[[ 6  8]
 [10 13]]


2. Subtract the two array.


In [41]:
print(x - y)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [42]:
print(x * 3)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.


In [43]:
print(np.square(x))

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


(a) v and w

In [44]:
print(np.dot(v, w))

219


(b) x and v

In [45]:
print(np.dot(x, v))

[29 77]


(c) x and y

In [46]:
print(np.dot(x, y))

[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.


In [47]:
print(np.column_stack((v, w)))

[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [48]:
print(np.concatenate((x, v)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Because:

x is 2D → shape (2,2)

v is 1D → shape (2,)

Different number of dimensions.

NumPy cannot concatenate arrays with different dimensions.

---
**Problem - 4: Matrix Operations:**

For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.



In [55]:
import numpy as np

# Define matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("========== MATRIX OPERATIONS ==========\n")

# 1️⃣ Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_result = A @ A_inv

print("1) Verifying A · A⁻¹ = I")
print("A⁻¹ =")
print(A_inv)

print("\nA · A⁻¹ =")
print(identity_result)

print("\nResult: A · A⁻¹ equals Identity?",
      np.allclose(identity_result, np.eye(2)))
print("\n---------------------------------------\n")

# 2️⃣ Prove AB ≠ BA
AB = A @ B
BA = B @ A

print("2) Verifying AB ≠ BA")
print("AB =")
print(AB)

print("\nBA =")
print(BA)

print("\nResult: AB equals BA?",
      np.array_equal(AB, BA))
print("\n---------------------------------------\n")

# 3️⃣ Prove (AB)ᵀ = BᵀAᵀ
left_side = (A @ B).T
right_side = B.T @ A.T

print("3) Verifying (AB)ᵀ = BᵀAᵀ")
print("(AB)ᵀ =")
print(left_side)

print("\nBᵀAᵀ =")
print(right_side)

print("\nResult: (AB)ᵀ equals BᵀAᵀ?",
      np.allclose(left_side, right_side))

print("\n========== END ==========")

========== MATRIX OPERATIONS ==========

1) Verifying A · A⁻¹ = I
A⁻¹ =
[[-2.    1.  ]
 [ 1.75 -0.75]]

A · A⁻¹ =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Result: A · A⁻¹ equals Identity? True

---------------------------------------

2) Verifying AB ≠ BA
AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

Result: AB equals BA? False

---------------------------------------

3) Verifying (AB)ᵀ = BᵀAᵀ
(AB)ᵀ =
[[23 51]
 [13 29]]

BᵀAᵀ =
[[23 51]
 [13 29]]

Result: (AB)ᵀ equals BᵀAᵀ? True

========== END ==========


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [56]:
import numpy as np

print("========== SOLVING LINEAR SYSTEM ==========\n")

# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

# Constant matrix B
B = np.array([-1, -3, 9])

print("Coefficient Matrix A:")
print(A)

print("\nConstant Vector B:")
print(B)

# ------------------------------------------------
# Method 1: Using Inverse
# ------------------------------------------------

A_inv = np.linalg.inv(A)
X_inverse = A_inv @ B

print("\n1) Solution using Inverse Method:")
print("X =", X_inverse)

# ------------------------------------------------
# Method 2: Using np.linalg.solve (Preferred)
# ------------------------------------------------

X_solve = np.linalg.solve(A, B)

print("\n2) Solution using np.linalg.solve():")
print("X =", X_solve)

print("\n========== END ==========")

========== SOLVING LINEAR SYSTEM ==========

Coefficient Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant Vector B:
[-1 -3  9]

1) Solution using Inverse Method:
X = [ 2.  1. -2.]

2) Solution using np.linalg.solve():
X = [ 2.  1. -2.]

========== END ==========


---
**10.2 Experiment: How Fast is Numpy?**

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [57]:
import numpy as np
import time

print("========== ELEMENT-WISE ADDITION ==========\n")

size = 1_000_000

# Python Lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")

# NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_array = arr1 + arr2
end = time.time()

print("NumPy Array Addition Time:", end - start, "seconds")

print("\n===========================================\n")

========== ELEMENT-WISE ADDITION ==========

Python List Addition Time: 0.12078118324279785 seconds
NumPy Array Addition Time: 0.007394313812255859 seconds




---
**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [58]:
print("========== ELEMENT-WISE MULTIPLICATION ==========\n")

# Python Lists
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")

# NumPy Arrays
start = time.time()
result_array = arr1 * arr2
end = time.time()

print("NumPy Array Multiplication Time:", end - start, "seconds")

print("\n================================================\n")

========== ELEMENT-WISE MULTIPLICATION ==========

Python List Multiplication Time: 0.4881761074066162 seconds
NumPy Array Multiplication Time: 0.007539033889770508 seconds




---
**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [59]:
print("========== DOT PRODUCT ==========\n")

# Python Lists
start = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")

# NumPy Arrays
start = time.time()
dot_product_array = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")

print("\n=================================\n")

========== DOT PRODUCT ==========

Python List Dot Product Time: 0.23143506050109863 seconds
NumPy Dot Product Time: 0.0030639171600341797 seconds




---
**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [60]:
print("========== MATRIX MULTIPLICATION ==========\n")

matrix_size = 1000

# Python Lists (very slow)
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

start = time.time()

result_matrix = [[sum(matrix1[i][k] * matrix2[k][j]
                      for k in range(matrix_size))
                  for j in range(matrix_size)]
                 for i in range(matrix_size)]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy Arrays
arr_matrix1 = np.array(matrix1)
arr_matrix2 = np.array(matrix2)

start = time.time()
result_numpy = arr_matrix1 @ arr_matrix2
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

print("\n=================================\n")

========== MATRIX MULTIPLICATION ==========

Python List Matrix Multiplication Time: 204.6692612171173 seconds
NumPy Matrix Multiplication Time: 2.687356472015381 seconds


